### ISSUE TITLE
Multiple selección menú

### ISSUE THREAD

**Issue by Leeoofeer** [TheoLeyenda/School-s-Out-#1]
Descripción:
--
En el menú al seleccionar una opción con el mouse y luego utilizar el teclado, aparecen dos opciones seleccionadas

Resolución:
--
Limitar la selección de menú a 1 solo ítem

[Video Drive](https://drive.google.com/open?id=1r9AJapTrMJCgPs5C-zy08uDG6Xj_Q4ga)

**Comment by TheoLeyenda** [comment]
Bug resuelto. hoy a la noche subo la nueva versión a itchio perdón por recién ahora responder... un saludo mis anónimos amigos
