### ISSUE TITLE
[A-PHASE] El jefe deja de atacar y se queda quieto

### ISSUE THREAD

**Issue by TomasJPereyra64** [TheoLeyenda/School-s-Out-#12]
Pasos para reproducir:
 - Llegar hasta un jefe
- Esperar a que deje de atacar

Resultado: El jefe se queda quieto y no vuelve a moverse o atacar.

Frecuencia de reproducción: Cada vez.

Link al bug: https://drive.google.com/open?id=1blQavvKPFli-y4QV1LHJEMJ2BPHs5BBH

**Comment by TheoLeyenda** [comment]
El Modo Historia no estara disponible para la entrega del segundo parcial de este proyecto sino para el final por lo tanto el error, sera arreglado para la entrega final de este juego.
