### ISSUE TITLE
No se puede abrir la nueva version del juego

### ISSUE THREAD

**Issue by TomasJPereyra64** [TheoLeyenda/School-s-Out-#13]
Al intentar abrir el juego salta un error, sin siquiera poder iniciarse. 

Link al bug: https://drive.google.com/open?id=1CUZHUc2aSKPyA3OjxMigGzetTi4c37qb

**Comment by TheoLeyenda** [comment]
Intenta bajártelo de nuevo seguramente te bajaste la build cuando yo la estaba subiendo a drive.
Te digo esto porque uno de mis artistas cuando se termino de subir la build probo que el juego se pudiera abrir y bajar con total funcionalidad.

**Comment by TheoLeyenda** [comment]
Si sigue pasando lo mismo avisame porfavor. gracias

**Comment by TomasJPereyra64** [comment]
Ahí funciono bien
