### ISSUE TITLE
Pantalla de victoria teclado no responde

### ISSUE THREAD

**Issue by Leeoofeer** [TheoLeyenda/School-s-Out-#2]
Descripción
--
Al ganar la partida (PVP) en la pantalla de victoria, el teclado es inutilizado pudiendo solo usar el mouse para navegar en las opciones que provee el menú de victoria

Resolución
--
Permitir navegar en los menús del juego mediante las flechas/mouse

[Video drive](https://drive.google.com/open?id=1RD9N2yP10bjVMNUnTfYROH-clnn40MO9)

**Comment by TheoLeyenda** [comment]
En la nueva version del juego que subiré esta noche todo el juego se controlara con controles de PS4 así que bug resuelto (El hecho de que todo el juego se maneje con controles de PS4 fue una decisión tomada por todo el equipo).
