### ISSUE TITLE
Agregar controles PVP

### ISSUE THREAD

**Issue by Leeoofeer** [TheoLeyenda/School-s-Out-#3]
Descripción
--
Permitir jugar con el teclado a ambos jugadores seria un super PLUS para las personas que no poseen dos joysticks

Resolución
--
Agregar como controles:
Jugador 1: W,A,S,D y I,J,K,L 
Jugador 2: UP-LEFT-DOWN-RIGHT y 5,1,2,3
O controles similares a los viejos juegos online 2 jugadores

**Comment by TheoLeyenda** [comment]
Me gustaron los controles nuevos, lo hablare con el equipo y por aquí te informare si al final el juego tendrá la opción de jugarse con teclado (En lo personal me asina la idea pero bueno somos cuatro en el equipo y no se si ellos también estén de acuerdo)
