### ISSUE TITLE
Trail de los ataques mas largo y con origen desconocido

### ISSUE THREAD

**Issue by Leeoofeer** [TheoLeyenda/School-s-Out-#7]
Descripción
--
El trail de los ataques aveces es generado de un punto desconocido, y cambia su tamaño cuando sale del piso, luego a veces sale de un punto lejos de la cabeza el ataque que es tipo mortero (chequear video )
Tambien sucede en #6 chequear su video

Resolución
--
Arreglar el origen y tamaño de los trail de los ataques

[Video drive](https://drive.google.com/open?id=1vjNI2uIVdXFhuOxLbbpiwcIBiLG0IvNf)

**Comment by TheoLeyenda** [comment]
El bug esta resuelto, ya no se generan trails desconocidos, lo que si debo aclarar es que el trail que se genera cuando haces un ataque en parábola, es mas grande por diseño, no por un bug.
